language: python

install:
  - pip install -r requirements.txt

python:
  - 3.6

services:
  - postgresql

env:
  - DJANGO=2.0 DB=postgresql SECRET_KEY='=xti712i87pm=a_wyq$chj8v)zqzzp))q1*5!padcx1yhx=%^)' DEBUG='True' ENGINE='django.db.backends.postgresql' DB_NAME='Project_Finder' DB_USER='postgres' DB_PASS='pass@123' DB_HOST='localhost' DB_PORT='5432'

before_install:
  - export DJANGO_SETTINGS_MODULE=project_finder.settings

before_script:
  - psql -c "CREATE DATABASE Project_Finder;" -U postgres
  - psql -c "CREATE USER root WITH CREATEUSER PASSWORD 'pass@123';" -U postgres
  - psql -c "ALTER USER root CREATEDB;" -U postgres
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - flake8
  - python3 manage.py test
